//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp1
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class upEntities : DbContext
    {
        private static upEntities _context;

        public upEntities()
            : base("name=upEntities")
        {
        }
        public static upEntities Context()
        {
            if (_context == null)
                _context = new upEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Hotel1> Hotel1 { get; set; }
        public virtual DbSet<HotelComment> HotelComment { get; set; }
        public virtual DbSet<HotelImage> HotelImage { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<type> type { get; set; }
    }
}
